### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by ruochenxing** [LiuXingMing/QQSpider#1]
你在爬去个人信息的时候有没有遇到受限的问题，就是爬一段时间之后个人信息就获取不到，貌似要到24小时候才能从新获取。

**Comment by LiuXingMing** [comment]
没有遇到过。你会调试吗，看一下它返回来的是什么内容？

**Comment by ruochenxing** [comment]
返回的是空字符串，并且这个时候如果我用浏览器登陆去查看好友的个人信息的话返回的也是空字符串，什么都没有。感觉腾讯做了获取个人信息的限制。。

**Comment by LiuXingMing** [comment]
你用浏览器去看的时候是打开他的空间还是打开代码里面的那个链接（代码里的链接是请求JS文件的链接）？还有你登录是用哪个QQ号登录去看的？用一个新的QQ登录看看，看腾讯限的是Q号还是IP？我暂时还没有遇到过这个问题。

**Comment by ruochenxing** [comment]
这个链接，http://base.s2.qzone.qq.com/cgi-bin/user/cgi_userinfo_get_all.....。仍然是同一个QQ。我觉得是做了QQ限制，因为我换一个QQ后还能继续获取，但是获取一段时间后就同样被限制了，真是醉了。。。。。

**Comment by LiuXingMing** [comment]
如果是限制了QQ的话就只能增加QQ了，或者加大请求的时间间隔了，我一般是 thread_num_QQ 开3或4个，登录的QQ有二十来个，并没有遇到限制的情况。

**Comment by ruochenxing** [comment]
😓，登录的QQ有二十来个 。。。。好吧。只能这样了。谢谢了
