### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by ABC0408** [LiuXingMing/QQSpider#3]
my_messages.backups()  # 备份爬虫信息
NameError: name 'my_messages' is not defined
这个该怎么解决啊，替换的那两个文件也不行，还是出现这个问题

**Comment by happy5035** [comment]
init_messages.InitMessages() 这个函数抛异常了，具体你看init_messages里面的init_qqbitset()函数，这个函数有问题~
