### ISSUE TITLE
有毒，安装好依赖后连不上队列

### ISSUE THREAD

**Issue by tetsaicn** [LiuXingMing/QQSpider#6]
Error 111 connecting to localhost:6379. Connection refused.
2017-01-01 21:11:06.821504
2017-01-01 21:11:06.821521: Done!

**Comment by LiuXingMing** [comment]
redis连接出问题，你先测试一下你的redis服务是否已经打开，用客户端或命令行是否能连上。



bone_ace@163.com
 
发件人： tetsaicn
发送时间： 2017-01-01 21:16
收件人： LiuXingMing/QQSpider
抄送： Subscribed
主题： [LiuXingMing/QQSpider] 有毒，安装好依赖后连不上队列 (#6)
Error 111 connecting to localhost:6379. Connection refused.
2017-01-01 21:11:06.821504
2017-01-01 21:11:06.821521: Done!
