### ISSUE TITLE
使用文档呢？

### ISSUE THREAD

**Issue by hktalent** [LiuXingMing/QQSpider#7]
使用文档呢？
1、pip 安装哪些依赖包啊？

2、依赖环境有哪些？
都需要安装哪些软件

3、初始化程序是哪个？

4、如何运行？

5、如何查看运行结果?

**Comment by LiuXingMing** [comment]
见：
http://blog.csdn.net/bone_ace/article/details/50771839
http://blog.csdn.net/Bone_ACE/article/details/53213779

**Comment by hktalent** [comment]
谢谢看了你的文档，补充给其他人参考
下面是mac os系统的安装
1、安装phantomjs、redis、MongoDB
brew install phantomjs
// http://phantomjs.org/download.html
brew install redis
brew services restart redis
brew install MongoDB
brew services restart MongoDB
2、安装python包
pip install requests BeautifulSoup multiprocessing selenium redis pymongo BitVector
itertools python内建无需安装
也就是itertools安装失败，在mac os下
3、MongoDB数据库工具
工具下载地址
http://m4.pc6.com/cjh3/mongobooster315.dmg

4、设置qq及密码
用于爬虫登录qq空间抓取信息
为什么不和数据库信息集中配置呢？
5、配置数据库信息
init_messages.py
self.thread_num_QQ   不明白，为什么不根据myQQ.txt行数自动设置？
self.thread_num_Blog 怎么设置为所有？
self.blog_after_date self.mood_after_date 能否设置为所有？

QQForSpider.txt 不设置能否爬取所有人？或者爬取一级好友、N级好友？

self.mongo['QQ'] 我本地已经有这个库了，要冲突啊
pymongo.MongoClient('localhost', 27017) 这些信息能否集中配置啊


6、bug？
i_login_uin=3352188148 这个参数写死了怕会被跟踪吧？
遇到另外一个问题
$ pip install  BitVector
Requirement already satisfied: BitVector in /Users/xxx/.pyenv/versions/2.7.13/lib/python2.7/site-packages
$ python ./init.py
raceback (most recent call last):
  File "./init.py", line 4, in <module>
    import init_messages
  File "/QQSpider/QQSpider1/init_messages.py", line 3, in <module>
    import BitVector
ImportError: No module named BitVector

**Comment by hktalent** [comment]
见前面一些过程记录、建议，以及报错，抱歉我对python不熟悉，遇到了一些问题，还需要你帮助

**Comment by zhugehui9527** [comment]
现在跑不起来了，个人信息 403
